### ISSUE TITLE
Configure Git settings on Pi

### ISSUE THREAD

**Issue by amolakplaha** [f-0-o/Smart-Trash-Can#43]
I accidentally wrote your name and email while setting up the repository on my Github. Can you please check if I fixed it?

**Comment by ffund** [comment]
@amolakplaha Do you mean this part?

![image](https://user-images.githubusercontent.com/2316553/156431916-e11922cb-8323-455c-bf3d-6d9fbd7ee993.png)

Re-running those command with the correct username and email should fix it.

This command determines how your contributions will appear when you commit and push code to Github! Since you haven't commited and pushed any code yet, we can't see how your contributions appear.

Mention me again (add a comment and reference `@ffund` in it) after you have commited and pushed some code, and then we'll see how that worked.

**Comment by amolakplaha** [comment]
I have committed and pushed code to Github. I was having some difficulting making the commitment to working however, after a little while I realized I wasn't in the correct directory! I tried doing the pull command and I am receiving this message. Could you tell me if this is what I am supposed to see and if not, how to fix it? @ffund 

This is the screenshot of what I get when I try to do a "pull"
<img width="1031" alt="Screen Shot 2022-03-07 at 10 43 18 PM" src="https://user-images.githubusercontent.com/98905458/157162364-518cdba3-6a0e-40b7-a69e-433c5eec8a37.png">

**Comment by amolakplaha** [comment]
I have configured my pi to Git. @f-0-o when you are done configuring your pi, put this issue in done.
